services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-server-java-paper
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"

      VERSION: "1.19.4"
      TYPE: "PAPER"
      SERVER_NAME: "N115 Minecraft Java Paper"
      MOTD: "First Peaceful World"

      # survival, creative, adventure
      GAMEMODE: "survival"
      # peaceful, easy, normal, hard
      DIFFICULTY: "peaceful"

      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: 2G

      # uncomment this to import a saved game. (put your savegame directory in the saves-to-import directory)
      # WORLD: "/worlds/My-World"

    volumes:
      - ~/minecraft-java-paper/data:/data
      - ~/minecraft-java-paper/worlds:/worlds:ro
