services:
  mc:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-server-bedrock
    ports:
      - 19132:19132/udp
    environment:
      EULA: "TRUE"

      VERSION: "1.16"
      TYPE: "PAPER"
      SERVER_NAME: "N115 Minecraft Bedrock"
      MOTD: "First Peaceful World"

      # survival, creative, adventure
      GAMEMODE: "survival"
      # peaceful, easy, normal, hard
      DIFFICULTY: "peaceful"

      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: 2G

      # uncomment this to import a saved game. (put your savegame directory in the saves-to-import directory)
      # WORLD: "/worlds/My-World"

    volumes:
      - ~/minecraft-bedrock/data:/data
      - ~/minecraft-bedrock/worlds:/worlds:ro
