services:
  crafty:
    container_name: crafty
    image: arcadiatechnology/crafty-4:4.4.4
    restart: always
    environment:
        - TZ=Europe/Berlin
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - $HOME/crafty/backups:/crafty/backups
        - $HOME/crafty/logs:/crafty/logs
        - $HOME/crafty/servers:/crafty/servers
        - $HOME/crafty/config:/crafty/app/config
        - $HOME/crafty/import:/crafty/import